project:
  type: website
  output-dir: docs
website:
  title: "Werbeagentur gründen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - phzh.qmd
      - aufgabe.qmd
      - theorie.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Zeige den ChatGPT-Prompt"
    link-external-icon: true
    link-external-newwindow: true
    
editor: visual

