project:
  type: website

website:
  title: "ph-workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - aufgabe.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Zeige den ChatGPT-Prompt"
    link-external-icon: true
    link-external-newwindow: true
    
editor: visual

